version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    environment:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
     - POSTGRES_DB
    ports:
      - "8000:8000"
    volumes:
      - .:/golibro
    tty: true
    restart: always
    depends_on:
      - redis
      - db
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
  db:
   image: postgres:13-alpine
   environment:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
     - POSTGRES_DB
   volumes:
     - data:/var/lib/postgresql/data
   expose:
     - "5432"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  celeryworker:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: sh -c "celery -A golibro.celeryconf beat -l info"
    volumes:
      - .:/hitiit360
    depends_on:
      - redis
      - db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - SECRET_KEY
      - DJANGO_SETTINGS_MODULE
    tty: true
  redis:
    image: redis:alpine
volumes:
  data: