# Generated by Django 4.2 on 2023-07-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('users', '0002_user_groups_user_is_active_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='has_bv_acheteur_access',
            new_name='has_bv_buyer_access',
        ),
        migrations.AlterField(
            model_name='contact',
            name='language_id',
            field=models.ForeignKey(blank=True, db_column='nLangue', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.language'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
