# Generated by Django 4.2 on 2023-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(db_column='icFrequence', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='cDescription', max_length=50, null=True)),
                ('description_an', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='cDescriptionAn', max_length=50, null=True)),
                ('month', models.IntegerField(blank=True, db_column='nMois', null=True)),
            ],
            options={
                'db_table': 'tblFrequence',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Frequence',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='poste_1',
            new_name='ext_1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='poste_2',
            new_name='ext_2',
        ),
    ]
